#THE CODE IMMEDIATELY BELOW HAS BEEN GENERATED BY AN AI MODEL ON THE ORDERS OF ALEXANDER
#AND MAY CONTAIN INACCURACIES OR ERRORS.
#PLEASE REVIEW CAREFULLY BEFORE USING OR SHARING THIS CODE.
#AI CODE STARTS HERE:
#' Trump's Truth Social Scraper
#'
#' Scrapes tweets from Trump's Truth Social (trumpstruth.org) within a specified
#' date range. Extracts text content, excludes media-only tweets, and outputs
#' to a chronologically ordered .txt file (oldest first).
#'
#' @docType package
#' @name TTruthPlotter
#'
#' @import httr2
#' @import xml2
#' @import dplyr
#' @import tibble
#' @import lubridate
#' @import stringr
NULL

# ============================================================================
# Package dependencies (install if needed)
# ============================================================================
# install.packages(c("httr2", "xml2", "dplyr", "tibble", "lubridate", "stringr"))

# ============================================================================
# 1. FETCH_POSTS_BY_DATE_RANGE
# ============================================================================

#' Fetch posts from Trump's Truth Social within a date range
#'
#' Scrapes all posts from the Trump's Truth Social search endpoint for the
#' specified date range. Implements page-based pagination with automatic
#' stopping when the final page is reached (fewer posts than per_page returned).
#'
#' @param start_date Date or character. Start date in YYYY-MM-DD format.
#'   Will be coerced to Date class via lubridate.
#' @param end_date Date or character. End date in YYYY-MM-DD format.
#'   Will be coerced to Date class via lubridate.
#' @param posts_per_page Numeric. Number of posts per page (default: 100).
#'   Must be in c(10, 25, 50, 100) based on site options.
#'
#' @return A tibble with columns:
#'   \item{date_time}{POSIXct: Post timestamp, parsed via lubridate}
#'   \item{text}{Character: Post text content (empty string if media-only)}
#'   \item{is_media_only}{Logical: TRUE if post contains only media, no text}
#'
#' @details
#' Pagination strategy:
#' - Loops through pages starting at page 1
#' - Stops when nrow(page_posts) < per_page (last page reached)
#' - Includes safety failsafe: stops if page > 500 (prevents infinite loops)
#' - If final page has exactly per_page posts, logs warning (rare edge case)
#' - Returns empty tibble if no posts found in date range
#'
#' @examples
#' \dontrun{
#'   # Fetch posts from May 1-4, 2026
#'   posts <- fetch_posts_by_date_range("2026-05-01", "2026-05-04")
#'   head(posts)
#' }
#'
#' @export
fetch_posts_by_date_range <- function(start_date,
                                       end_date,
                                       posts_per_page = 100) {

  # Validate and coerce dates
  start_date <- lubridate::ymd(start_date)
  end_date <- lubridate::ymd(end_date)

  if (is.na(start_date) || is.na(end_date)) {
    stop("Invalid date format. Use YYYY-MM-DD or provide Date objects.")
  }

  if (start_date > end_date) {
    stop("start_date must be before or equal to end_date.")
  }

  # Initialize
  all_posts <- tibble::tibble()
  page <- 1
  max_pages <- 500
  posts_per_page <- as.integer(posts_per_page)

  message(
    sprintf(
      "Fetching posts from %s to %s (%d per page)...",
      start_date, end_date, posts_per_page
    )
  )

  # Pagination loop
  while (page <= max_pages) {
    # Construct base URL and query parameters
    base_url <- "https://www.trumpstruth.org/search"
    
    # Start building request with query parameters
    req <- httr2::request(base_url) |>
      httr2::req_url_query(
        query = "",
        start_date = format(start_date, "%Y-%m-%d"),
        end_date = format(end_date, "%Y-%m-%d"),
        sort = "date_desc",
        removed = "include",
        per_page = posts_per_page
      )
    
    # Add page parameter only for page > 1
    if (page > 1) {
      req <- req |>
        httr2::req_url_query(page = page)
    }

    # Fetch page
    tryCatch(
      {
        response <- req |>
          httr2::req_perform()

        html <- response |>
          httr2::resp_body_html()

        # Extract all posts from this page
        posts_nodes <- html |>
          xml2::xml_find_all(".//div[@class='search-result']")

        # Parse posts
        page_posts <- tibble::tibble()

        for (post_node in posts_nodes) {
          # Extract date/time
          date_text <- tryCatch(
            {
              post_node |>
                xml2::xml_find_first(
                  ".//div[@class='status-info__meta']//a[@class='status-info__meta-item'][2]"
                ) |>
                xml2::xml_text() |>
                stringr::str_trim()
            },
            error = function(e) NA_character_
          )

          # Extract text content
          text_content <- tryCatch(
            {
              post_node |>
                xml2::xml_find_first(".//div[@class='snippet-clean-content']") |>
                xml2::xml_text() |>
                stringr::str_trim()
            },
            error = function(e) NA_character_

            #error = function(e) {
            #   message("Text extraction failed: ", conditionMessage(e))
            #  NA_character_
            #}

          )

          # Determine if media-only (empty text or NA)
          is_media_only <- is.na(text_content) || text_content == ""


          # Parse datetime
          parsed_date <- tryCatch(
            {
              # Try parsing with lubridate (handles various formats)
              lubridate::parse_date_time(
                date_text,
                orders = c("b d, Y H:M p", "Y-m-d H:M p")
              )
            },
            error = function(e) {
              warning(sprintf("Could not parse date: %s", date_text))
              lubridate::as_datetime(NA)
            }
          )

          # Add to page_posts
          page_posts <- page_posts |>
            dplyr::bind_rows(
              tibble::tibble(
                date_time = parsed_date,
                text = text_content,
                is_media_only = is_media_only
              )
            )
        }

        # Bind to all_posts
        all_posts <- all_posts |>
          dplyr::bind_rows(page_posts)

        posts_count <- nrow(page_posts)
        message(sprintf("  Page %d: fetched %d posts", page, posts_count))

        # Check if last page: if fewer posts than per_page, stop
        if (posts_count < posts_per_page) {
          if (posts_count == posts_per_page && page > 1) {
            warning(
              sprintf(
                "Final page (%d) returned exactly per_page (%d) posts. ",
                "This is a rare edge case; verify no additional posts exist.",
                page, posts_per_page
              )
            )
          }
          message(sprintf("Pagination complete. Total pages: %d", page))
          break
        }

        page <- page + 1
      },
      error = function(e) {
        warning(sprintf("Error fetching page %d: %s", page, conditionMessage(e)))
      }
    )
  }

  if (page > max_pages) {
    warning(sprintf("Reached max_pages limit (%d). Pagination stopped.", max_pages))
  }

  message(
    sprintf(
      "Total posts fetched: %d (%d media-only)",
      nrow(all_posts),
      sum(all_posts$is_media_only, na.rm = TRUE)
    )
  )

  return(all_posts)
}

# ============================================================================
# 2. FILTER_TEXT_TWEETS
# ============================================================================

#' Filter out media-only tweets
#'
#' Removes tweets that contain only media (images/videos) with no text content.
#' Keeps tweets that have text, even if they also contain media.
#'
#' @param posts_tibble Tibble from fetch_posts_by_date_range()
#'
#' @return Filtered tibble containing only text tweets (is_media_only == FALSE)
#'
#' @examples
#' \dontrun{
#'   posts <- fetch_posts_by_date_range("2026-05-01", "2026-05-04")
#'   text_tweets <- filter_text_tweets(posts)
#' }
#'
#' @export
filter_text_tweets <- function(posts_tibble) {
  posts_tibble |>
    dplyr::filter(!is_media_only)
}

# ============================================================================
# 3. SORT_CHRONOLOGICAL
# ============================================================================

#' Sort tweets in chronological order
#'
#' Sorts the tweet tibble by date_time, with oldest posts first (ascending).
#'
#' @param posts_tibble Tibble with date_time column
#' @param oldest_first Logical. If TRUE (default), sorts ascending (oldest first).
#'   If FALSE, sorts descending (newest first).
#'
#' @return Tibble sorted by date_time
#'
#' @examples
#' \dontrun{
#'   posts <- fetch_posts_by_date_range("2026-05-01", "2026-05-04")
#'   text_tweets <- filter_text_tweets(posts)
#'   sorted_posts <- sort_chronological(text_tweets)
#' }
#'
#' @export
sort_chronological <- function(posts_tibble, oldest_first = TRUE) {
  if (oldest_first) {
    posts_tibble |>
      dplyr::arrange(date_time)
  } else {
    posts_tibble |>
      dplyr::arrange(dplyr::desc(date_time))
  }
}

# ============================================================================
# 4. FORMAT_OUTPUT
# ============================================================================

#' Format tweets for text file output
#'
#' Converts the sorted posts tibble into a character vector suitable for
#' writing to a .txt file.
#'
#' @param posts_tibble Tibble with date_time and text columns (already sorted)
#' @param include_date_headers Logical. If TRUE, includes date headers
#'   (one header per date). Default is FALSE (one tweet per line).
#'
#' @return Character vector where each element is a tweet (or header, if enabled)
#'
#' @details
#' Default format (include_date_headers = FALSE):
#'   - One tweet per line
#'   - Tweets separated by blank lines
#'   - No headers
#'
#' With headers (include_date_headers = TRUE):
#'   - Group tweets by date
#'   - Add "--- YYYY-MM-DD ---" header before each date's tweets
#'   - One tweet per line within each group
#'
#' @examples
#' \dontrun{
#'   posts <- fetch_posts_by_date_range("2026-05-01", "2026-05-04")
#'   text_tweets <- filter_text_tweets(posts)
#'   sorted_posts <- sort_chronological(text_tweets)
#'   formatted <- format_output(sorted_posts, include_date_headers = FALSE)
#' }
#'
#' @export
format_output <- function(posts_tibble, include_date_headers = FALSE) {
  if (nrow(posts_tibble) == 0) {
    return(character(0))
  }

  if (!include_date_headers) {
    # Simple format: one tweet per line with blank line separator
    tweets <- posts_tibble$text
    # Alternate tweets with blank lines
    output <- character(length(tweets) * 2 - 1)
    output[seq(1, length(tweets) * 2 - 1, 2)] <- tweets
    output[seq(2, length(tweets) * 2 - 1, 2)] <- ""
    return(output)
  } else {
    # Format with date headers
    posts_tibble <- posts_tibble |>
      dplyr::mutate(
        date_only = lubridate::date(date_time)
      )

    output <- character()

    current_date <- NULL
    for (i in seq_len(nrow(posts_tibble))) {
      row <- posts_tibble[i, ]
      row_date <- row$date_only[[1]]

      # Add date header if date changed
      if (is.null(current_date) || row_date != current_date) {
        output <- c(output, sprintf("--- %s ---", row_date))
        current_date <- row_date
      }

      # Add tweet
      output <- c(output, row$text[[1]])
      # Add blank line
      output <- c(output, "")
    }

    return(output)
  }
}

# ============================================================================
# 5. SAVE_TWEETS_TO_FILE
# ============================================================================

#' Save formatted tweets to a text file
#'
#' Writes the formatted tweet vector to a .txt file in the working directory.
#'
#' @param formatted_text Character vector from format_output()
#' @param filename Character. Output filename (default: "tweets.txt").
#'   Will be saved in current working directory.
#'
#' @return Invisibly returns the file path (for verification)
#'
#' @examples
#' \dontrun{
#'   posts <- fetch_posts_by_date_range("2026-05-01", "2026-05-04")
#'   text_tweets <- filter_text_tweets(posts)
#'   sorted_posts <- sort_chronological(text_tweets)
#'   formatted <- format_output(sorted_posts)
#'   save_tweets_to_file(formatted, "output_tweets.txt")
#' }
#'
#' @export
save_tweets_to_file <- function(formatted_text, filename = "tweets.txt") {
  output_path <- file.path(getwd(), filename)

  tryCatch(
    {
      writeLines(formatted_text, output_path, useBytes = TRUE)
      message(sprintf("Tweets saved to: %s", output_path))
      invisible(output_path)
    },
    error = function(e) {
      stop(sprintf("Error saving file: %s", conditionMessage(e)))
    }
  )
}

# ============================================================================
# 6. SCRAPE_TRUTH_SOCIAL_TWEETS (Main Orchestration Function)
# ============================================================================

#' Scrape Trump's Truth Social tweets and save to file
#'
#' Main function that orchestrates the entire pipeline: fetch posts,
#' filter media-only tweets, sort chronologically, format, and save to file.
#'
#' @param start_date Date or character. Start date (YYYY-MM-DD format)
#' @param end_date Date or character. End date (YYYY-MM-DD format)
#' @param output_filename Character. Output .txt filename (default: "tweets.txt")
#' @param include_date_headers Logical. Include date headers in output
#'   (default: FALSE)
#' @param posts_per_page Numeric. Posts per page (default: 100)
#'
#' @return Invisibly returns the output file path. As a side effect, prints
#'   a summary of the scraping operation and saves tweets to file.
#'
#' @details
#' This is the main user-facing function. It chains together all modular
#' functions in the correct order and provides informative logging.
#'
#' Summary printed includes:
#' - Total posts fetched
#' - Posts filtered (media-only)
#' - Text posts kept
#' - Date range of output
#' - Output file location
#'
#' @examples
#' \dontrun{
#'   # Scrape tweets from May 1-4, 2026
#'   scrape_truth_social_tweets(
#'     start_date = "2026-05-01",
#'     end_date = "2026-05-04",
#'     output_filename = "may_tweets.txt"
#'   )
#'
#'   # Scrape with date headers
#'   scrape_truth_social_tweets(
#'     start_date = "2026-05-01",
#'     end_date = "2026-05-04",
#'     include_date_headers = TRUE
#'   )
#' }
#'
#' @export
scrape_truth_social_tweets <- function(start_date,
                                        end_date,
                                        output_filename = "tweets.txt",
                                        include_date_headers = FALSE,
                                        posts_per_page = 100) {

  message("\n========== TRUMP'S TRUTH SOCIAL SCRAPER ==========\n")

  # Fetch posts
  all_posts <- fetch_posts_by_date_range(
    start_date,
    end_date,
    posts_per_page
  )

  if (nrow(all_posts) == 0) {
    message("No posts found in the specified date range.")
    return(invisible(NULL))
  }

  # Count media-only
  media_only_count <- sum(all_posts$is_media_only, na.rm = TRUE)

  # Filter text tweets
  text_posts <- filter_text_tweets(all_posts)

  message(sprintf(
    "Filtered: %d media-only tweets removed, %d text tweets retained",
    media_only_count,
    nrow(text_posts)
  ))

  # Sort chronologically (oldest first)
  sorted_posts <- sort_chronological(text_posts, oldest_first = TRUE)

  # Format output
  formatted <- format_output(sorted_posts, include_date_headers)

  # Save to file
  output_path <- save_tweets_to_file(formatted, output_filename)

  # Print summary
  date_range <- sprintf(
    "%s to %s",
    min(sorted_posts$date_time, na.rm = TRUE),
    max(sorted_posts$date_time, na.rm = TRUE)
  )

  message("\n========== SUMMARY ==========")
  message(sprintf("Total posts fetched: %d", nrow(all_posts)))
  message(sprintf("Media-only tweets filtered: %d", media_only_count))
  message(sprintf("Text tweets in output: %d", nrow(text_posts)))
  message(sprintf("Date range (output): %s", date_range))
  message(sprintf("Output file: %s", output_filename))
  message("=============================\n")

  invisible(output_path)
}

# ============================================================================
# TEST / EXAMPLE USAGE
# ============================================================================
# Uncomment below to test with a known date range:

scrape_truth_social_tweets(
  start_date = "2026-06-01",
  end_date = "2026-06-07",

  #WE WILL ASK THE USER TO PROVIDE THE DATE RANGE THEY WANT TO SCRAPE:
  #start_date = readline(prompt = "Enter start date (YYYY-MM-DD): "),
  #end_date = readline(prompt = "Enter end date (YYYY-MM-DD): "),
  
  output_filename = "truth_tweets.txt",
  include_date_headers = FALSE
  
)
#THE AI CODE ENDS HERE.

#Now that we have the main scraping function,
# let's run some sentiment analysis on the tweets.
#I'll be using the code made by Zuzia & GPT
# to perform sentiment analysis on the scraped tweets.
#ZUZIA'S CODE:


# Projekt: system do analizy wpisów z pliku tekstowego ----
# Cel programu:
# 1) wczytać wpisy z pliku .txt,
# 2) oczyścić tekst metodami z zajęć: tokenizacja, stopwords, stemming, stemCompletion,
# 3) wykryć główny przedmiot tematyczny na podstawie najczęściej występujących słów,
# 4) wykonać analizę sentymentu i ocenić podejście autora do tematu.


# Wymagane pakiety ----
# install.packages(c("tm", "tidytext", "stringr", "wordcloud", "RColorBrewer",
#                    "ggplot2", "SnowballC", "SentimentAnalysis", "ggthemes", "tidyverse"))
library(tm)
library(tidytext)
library(stringr)
library(wordcloud)
library(RColorBrewer)
library(ggplot2)
library(SnowballC)
library(SentimentAnalysis)
library(ggthemes)
library(tidyverse)


# 0. Funkcja do przetwarzania tekstu z apostrofami, stemmingiem i stemCompletion ----
# Funkcja zostawiona w tej samej treści jak w skrypcie z zajęć.
process_text <- function(file_path) {
  text <- tolower(readLines(file_path, encoding = "UTF-8"))
  text <- gsub("[\u2019\u2018\u0060\u00B4]", "'", text)
  text <- removeNumbers(text)
  words <- unlist(strsplit(text, "\\s+"))
  words <- words[words != ""]
  words <- words[!str_detect(words, "'")]
  words <- str_replace_all(words, "[[:punct:]]", "")
  words <- words[words != ""]
  words <- str_trim(words)
  
  tidy_stopwords <- tolower(stop_words$word)
  tidy_stopwords <- gsub("[\u2019\u2018\u0060\u00B4]", "'", tidy_stopwords)
  tm_stopwords <- tolower(stopwords("en"))
  tm_stopwords <- gsub("[\u2019\u2018\u0060\u00B4]", "'", tm_stopwords)
  
  words <- words[!(words %in% tidy_stopwords)]
  words <- words[!(words %in% tm_stopwords)]
  
  # Stemming + stem completion
  stemmed_doc <- stemDocument(words)
  completed_doc <- stemCompletion(stemmed_doc, dictionary=words, type="prevalent")
  completed_doc <- completed_doc[completed_doc != ""]
  
  return(completed_doc)
}


# 0. Funkcja do obliczania częstości występowania słów ----
# Funkcja zostawiona w tej samej treści jak w skrypcie z zajęć.
word_frequency <- function(words) {
  freq <- table(words)
  freq_df <- data.frame(word = names(freq), freq = as.numeric(freq))
  freq_df <- freq_df[order(-freq_df$freq), ]
  return(freq_df)
}


# 0. Funkcja do tworzenia chmury słów ----
# Funkcja zostawiona w tej samej treści jak w skrypcie z zajęć.
plot_wordcloud <- function(freq_df, title, color_palette = "Dark2") {
  wordcloud(words = freq_df$word, freq = freq_df$freq, min.freq = 16,
            colors = brewer.pal(8, color_palette))
  title(title)
}


# Funkcja do dzielenia tekstu na segmenty o określonej długości ----
# Funkcja ze skryptu „Analiza sentymentu w czasie”.
split_text_into_chunks <- function(text, chunk_size) {
  start_positions <- seq(1, nchar(text), by = chunk_size)
  chunks <- substring(text, start_positions, start_positions + chunk_size - 1)
  return(chunks)
}


# 1. Wczytanie treści ----
# Wybierz plik .txt z treściami.
file_path <- "truth_tweets.txt"

# Wczytanie oryginalnego tekstu do analizy sentymentu w czasie.
text <- readLines(file_path, encoding="UTF-8")


# 2. Przetwarzanie i oczyszczanie tekstu ----
words <- process_text(file_path)

# Dodatkowe niestandardowe stopwords, tak jak w skryptach z zajęć.
# Tu można dopisać np. imię autora, nazwę portalu, zbędne symbole itd.
custom_stopwords <- c("—", "–", "’s", "’re", "$")
words <- words[!words %in% custom_stopwords]


# 3. Wykrywanie głównego przedmiotu tematycznego treści ----
# Założenie: główny temat to najczęściej występujące słowo/pojęcie po oczyszczeniu tekstu.
freq_df <- word_frequency(words)

cat("\nNAJCZĘŚCIEJ WYSTĘPUJĄCE SŁOWA WE WPISACH:\n")
print(head(freq_df, 20))

main_topic <- freq_df$word[1]
cat("\nGŁÓWNY PRZEDMIOT TEMATYCZNY WPISÓW:", main_topic, "\n")

# Chmura słów jako wizualizacja tematu.
plot_wordcloud(freq_df, "Chmura słów - główny temat wpisów", "Dark2")

# Wykres 20 najczęstszych słów.
top_words <- head(freq_df, 20)
top_words$word2 <- factor(top_words$word, levels = rev(top_words$word))

ggplot(top_words, aes(x = word2, y = freq)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(title = "20 najczęściej występujących słów",
       x = "Słowo",
       y = "Liczba wystąpień") +
  theme_gdocs()


# 4. Analiza sentymentu słownikami CSV ----
# Program korzysta ze słowników z zajęć: afinn.csv, bing.csv, loughran.csv, nrc.csv.
# Pliki CSV powinny być w tym samym folderze roboczym co skrypt albo należy wskazać poprawną ścieżkę.
# Jeśli plików CSV nie ma, program pobierze słowniki przez tidytext::get_sentiments().

afinn <- read.csv("afinn.csv", stringsAsFactors = FALSE)
bing <- read.csv("bing.csv", stringsAsFactors = FALSE)
loughran <- read.csv("loughran.csv", stringsAsFactors = FALSE)
nrc <- read.csv("nrc.csv", stringsAsFactors = FALSE)


tidy_tokeny <- as_tibble(freq_df)


# Analiza sentymentu przy użyciu słownika Loughran ----
sentiment_review <- tidy_tokeny %>%
  inner_join(loughran, relationship = "many-to-many")

cat("\nSENTYMENT - LOUGHRAN:\n")
print(sentiment_review %>% count(sentiment))

sentiment_review2 <- sentiment_review %>%
  filter(sentiment %in% c("positive", "negative"))

word_counts <- sentiment_review2 %>%
  group_by(sentiment) %>%
  top_n(20, freq) %>%
  ungroup() %>%
  arrange(desc(freq), word) %>%
  mutate(
    word2 = factor(word, levels = rev(unique(word)))
  )

if (nrow(word_counts) > 0) {
  ggplot(word_counts[1:min(30, nrow(word_counts)),], aes(x=word2, y=freq, fill=sentiment)) + 
    geom_col(show.legend=FALSE) +
    facet_wrap(~sentiment, scales="free") +
    coord_flip() +
    labs(x = "Słowa", y = "Liczba") +
    theme_gdocs() + 
    ggtitle("Liczba słów wg sentymentu (Loughran)") +
    scale_fill_manual(values = c("firebrick", "darkolivegreen4"))
}


# Analiza sentymentu przy użyciu słownika NRC ----
sentiment_review_nrc <- tidy_tokeny %>%
  inner_join(nrc, relationship = "many-to-many")

cat("\nSENTYMENT - NRC:\n")
print(sentiment_review_nrc %>% count(sentiment))

sentiment_review_nrc2 <- sentiment_review_nrc %>%
  filter(sentiment %in% c("positive", "negative"))

word_counts_nrc2 <- sentiment_review_nrc2 %>%
  group_by(sentiment) %>%
  top_n(20, freq) %>%
  ungroup() %>%
  arrange(desc(freq), word) %>%
  mutate(
    word2 = factor(word, levels = rev(unique(word)))
  )

if (nrow(word_counts_nrc2) > 0) {
  ggplot(word_counts_nrc2[1:min(30, nrow(word_counts_nrc2)),], aes(x=word2, y=freq, fill=sentiment)) + 
    geom_col(show.legend=FALSE) +
    facet_wrap(~sentiment, scales="free") +
    coord_flip() +
    labs(x = "Słowa", y = "Liczba") +
    theme_gdocs() + 
    ggtitle("Liczba słów wg sentymentu (NRC)")
}


# Analiza sentymentu przy użyciu słownika Bing ----
sentiment_review_bing <- tidy_tokeny %>%
  inner_join(bing, relationship = "many-to-many")

cat("\nSENTYMENT - BING:\n")
print(sentiment_review_bing %>% count(sentiment))

sentiment_review_bing2 <- sentiment_review_bing %>%
  filter(sentiment %in% c("positive", "negative"))

word_counts_bing2 <- sentiment_review_bing2 %>%
  group_by(sentiment) %>%
  top_n(20, freq) %>%
  ungroup() %>%
  arrange(desc(freq), word) %>%
  mutate(
    word2 = factor(word, levels = rev(unique(word)))
  )

if (nrow(word_counts_bing2) > 0) {
  ggplot(word_counts_bing2[1:min(30, nrow(word_counts_bing2)),], aes(x=word2, y=freq, fill=sentiment)) + 
    geom_col(show.legend=FALSE) +
    facet_wrap(~sentiment, scales="free") +
    coord_flip() +
    labs(x = "Słowa", y = "Liczba") +
    theme_gdocs() + 
    ggtitle("Liczba słów wg sentymentu (Bing)") +
    scale_fill_manual(values = c("dodgerblue4", "goldenrod1"))
}


# Analiza sentymentu przy użyciu słownika Afinn ----
sentiment_review_afinn <- tidy_tokeny %>%
  inner_join(afinn, relationship = "many-to-many")

cat("\nSENTYMENT - AFINN:\n")
print(summary(sentiment_review_afinn$value))

score_afinn <- sum(sentiment_review_afinn$value * sentiment_review_afinn$freq, na.rm = TRUE)
cat("\nŁĄCZNY WYNIK AFINN:", score_afinn, "\n")

word_counts_afinn <- sentiment_review_afinn %>%
  mutate(sentyment = ifelse(value > 0, "positive", "negative")) %>%
  group_by(sentyment) %>%
  top_n(20, freq) %>%
  ungroup() %>%
  arrange(desc(freq), word) %>%
  mutate(word2 = factor(word, levels = rev(unique(word))))

if (nrow(word_counts_afinn) > 0) {
  ggplot(word_counts_afinn[1:min(30, nrow(word_counts_afinn)),], aes(x=word2, y=freq, fill=sentyment)) + 
    geom_col(show.legend=FALSE) +
    facet_wrap(~sentyment, scales="free") +
    coord_flip() +
    labs(x = "Słowa", y = "Liczba") +
    theme_gdocs() + 
    ggtitle("Liczba słów wg sentymentu (Afinn)")
}


# 5. Ocena podejścia autora do głównego tematu ----
# Liczymy przewagę słów pozytywnych lub negatywnych w słowniku Bing.
bing_summary <- sentiment_review_bing2 %>%
  group_by(sentiment) %>%
  summarise(total = sum(freq), .groups = "drop")

positive_count <- ifelse("positive" %in% bing_summary$sentiment,
                         bing_summary$total[bing_summary$sentiment == "positive"], 0)
negative_count <- ifelse("negative" %in% bing_summary$sentiment,
                         bing_summary$total[bing_summary$sentiment == "negative"], 0)

cat("\nPODSUMOWANIE PODEJŚCIA AUTORA DO TEMATU:\n")
cat("Główny temat:", main_topic, "\n")
cat("Liczba słów pozytywnych:", positive_count, "\n")
cat("Liczba słów negatywnych:", negative_count, "\n")

if (positive_count > negative_count) {
  author_attitude <- "pozytywne"
  cat("Wniosek: autor stosuje przeważnie język pozytywny, więc jego podejście do tematu można określić jako pozytywne.\n")
} else if (negative_count > positive_count) {
  author_attitude <- "negatywne"
  cat("Wniosek: autor stosuje przeważnie język negatywny, więc jego podejście do tematu można określić jako negatywne.\n")
} else {
  author_attitude <- "neutralne / niejednoznaczne"
  cat("Wniosek: liczba słów pozytywnych i negatywnych jest podobna, więc podejście autora jest neutralne albo niejednoznaczne.\n")
}


# 6. Analiza sentymentu w czasie przy użyciu SentimentAnalysis ----
# Usunięcie pustych wierszy
non_empty_lines <- text[nzchar(text)]

# Połączenie wszystkich wierszy w jeden ciąg znaków
full_text <- paste(non_empty_lines, collapse = " ")

# Usunięcie zbędnych spacji
full_text <- gsub("\\s+", " ", full_text)

# Podzielenie tekstu na segmenty
min_length <- 50
text_chunks <- split_text_into_chunks(full_text, min_length)

# Analiza sentymentu przy użyciu pakietu SentimentAnalysis
sentiment <- analyzeSentiment(text_chunks)

# Wczytanie słowników z pakietu SentimentAnalysis
data(DictionaryGI)
data(DictionaryHE)
data(DictionaryLM)
qdap <- loadDictionaryQDAP()

# Konwersja ciągłych wartości sentymentu na wartości kierunkowe
sentimentGI <- convertToDirection(sentiment$SentimentGI)
sentimentHE <- convertToDirection(sentiment$SentimentHE)
sentimentLM <- convertToDirection(sentiment$SentimentLM)
sentimentQDAP <- convertToDirection(sentiment$SentimentQDAP)

# Ramki danych do wykresów słupkowych
df_GI <- data.frame(index = seq_along(sentimentGI), value = sentimentGI, Dictionary = "GI")
df_GI <- na.omit(df_GI)

df_HE <- data.frame(index = seq_along(sentimentHE), value = sentimentHE, Dictionary = "HE")
df_HE <- na.omit(df_HE)

df_LM <- data.frame(index = seq_along(sentimentLM), value = sentimentLM, Dictionary = "LM")
df_LM <- na.omit(df_LM)

df_QDAP <- data.frame(index = seq_along(sentimentQDAP), value = sentimentQDAP, Dictionary = "QDAP")
df_QDAP <- na.omit(df_QDAP)

# Porównanie sentymentu na podstawie różnych słowników
df_all_bar <- bind_rows(df_GI, df_HE, df_LM, df_QDAP)

ggplot(df_all_bar, aes(x = value, fill = Dictionary)) +
  geom_bar(alpha = 0.7) + 
  labs(title = "Skumulowany sentyment według słowników",
       x = "Sentyment",
       y = "Liczba") +
  theme_bw() +
  facet_wrap(~Dictionary) +
  scale_fill_manual(values = c("GI" = "green", 
                               "HE" = "blue", 
                               "LM" = "orange",
                               "QDAP" = "red" ))


# Agregowanie sentymentu z różnych słowników w czasie ----
df_all <- data.frame(sentence=1:length(sentiment[,1]),
                     GI=sentiment$SentimentGI, 
                     HE=sentiment$SentimentHE, 
                     LM=sentiment$SentimentLM,
                     QDAP=sentiment$SentimentQDAP)

# Usunięcie pustych obserwacji np. dla zmiennej QDAP
df_all <- df_all[!is.na(df_all$QDAP), ]

# Wykres zmiany sentymentu w czasie
ggplot(df_all, aes(x=sentence, y=QDAP)) +
  geom_line(color="red", size=1) +
  geom_line(aes(x=sentence, y=GI), color="green", size=1) +
  geom_line(aes(x=sentence, y=HE), color="blue", size=1) +
  geom_line(aes(x=sentence, y=LM), color="orange", size=1) +
  labs(x = "Oś czasu segmentów tekstu", y = "Sentyment") +
  theme_gdocs() + 
  ggtitle("Zmiana sentymentu w czasie")


ggplot(df_all, aes(x=sentence, y=QDAP)) + 
  geom_smooth(color="red") +
  geom_smooth(aes(x=sentence, y=GI), color="green") +
  geom_smooth(aes(x=sentence, y=HE), color="blue") +
  geom_smooth(aes(x=sentence, y=LM), color="orange") +
  labs(x = "Oś czasu segmentów tekstu", y = "Sentyment") +
  theme_gdocs() + 
  ggtitle("Zmiana sentymentu w czasie - wygładzenie")


# 7. Końcowy raport tekstowy ----
# Ten fragment jest dopisany na sam koniec programu.
# Ma odpowiedzieć prostym językiem:
# - o czym przedmiotowo są wpisy,
# - jaki stosunek do tego tematu ma autor.
# Jest to rozwiązanie uniwersalne: temat może dotyczyć polityki, jedzenia,
# sportu, kultury, ekonomii albo dowolnego innego zagadnienia.

# Główny temat ustalamy na podstawie najczęstszych słów po oczyszczeniu tekstu,
# usunięciu stopwords, stemmingu i stemCompletion.
# Nie zakładamy z góry, czego dotyczą wpisy
top_topic_words <- head(freq_df$word, 5)
main_topic_sentence <- paste(top_topic_words, collapse = ", ")

# Funkcja pomocnicza: liczy sentyment w pobliżu słów tematycznych.
# Dzięki temu oceniamy stosunek autora nie tylko w całym pliku,
# ale przede wszystkim w sąsiedztwie głównego przedmiotu tekstu.
context_sentiment <- function(words, target_words, bing, window = 6) {
  positions <- which(words %in% target_words)
  if (length(positions) == 0) {
    return(data.frame(sentiment = c("positive", "negative"), total = c(0, 0)))
  }
  context_positions <- unique(unlist(lapply(positions, function(i) {
    max(1, i - window):min(length(words), i + window)
  })))
  context_words <- words[context_positions]
  context_df <- data.frame(word = context_words)
  context_sent <- context_df %>%
    inner_join(bing, relationship = "many-to-many") %>%
    filter(sentiment %in% c("positive", "negative")) %>%
    count(sentiment, name = "total")
  context_sent <- full_join(data.frame(sentiment = c("positive", "negative")),
                            context_sent, by = "sentiment")
  context_sent$total[is.na(context_sent$total)] <- 0
  return(context_sent)
}

# Sentyment bezpośrednio wokół głównego tematu wpisów
topic_context <- context_sentiment(words, top_topic_words, bing)
topic_positive <- topic_context$total[topic_context$sentiment == "positive"]
topic_negative <- topic_context$total[topic_context$sentiment == "negative"]
topic_score <- topic_positive - topic_negative

# Ogólny sentyment całego pliku tekstowego traktujemy jako wynik pomocniczy.
general_score <- positive_count - negative_count

# Główna interpretacja stosunku autora do tematu.
# Najważniejszy jest sentyment w pobliżu słów tematycznych.
# Jeżeli w pobliżu tematu nie ma słów ze słownika sentymentu,
# wtedy program korzysta z ogólnego sentymentu całego pliku tekstowego
if (topic_positive + topic_negative > 0) {
  if (topic_score > 0) {
    final_attitude <- "pozytywny"
    attitude_explanation <- "w sąsiedztwie słów opisujących główny temat częściej pojawia się język pozytywny niż negatywny."
  } else if (topic_score < 0) {
    final_attitude <- "negatywny"
    attitude_explanation <- "w sąsiedztwie słów opisujących główny temat częściej pojawia się język negatywny niż pozytywny."
  } else {
    final_attitude <- "neutralny albo niejednoznaczny"
    attitude_explanation <- "w sąsiedztwie słów opisujących główny temat liczba słów pozytywnych i negatywnych jest taka sama."
  }
} else {
  if (general_score > 0) {
    final_attitude <- "pozytywny"
    attitude_explanation <- "przy samym temacie nie wykryto słów sentymentalnych, więc wniosek oparto na przewadze słów pozytywnych w całym pliku tekstowym"
  } else if (general_score < 0) {
    final_attitude <- "negatywny"
    attitude_explanation <- "przy samym temacie nie wykryto słów sentymentalnych, więc wniosek oparto na przewadze słów negatywnych w całym pliku tekstowym."
  } else {
    final_attitude <- "neutralny albo niejednoznaczny"
    attitude_explanation <- "ani przy temacie, ani w całym pliku tekstowym nie widać wyraźnej przewagi języka pozytywnego lub negatywnego."
  }
}

# Zdanie interpretacyjne tworzone automatycznie dla dowolnego tematu.
final_interpretation <- paste0(
  "Plik tekstowy wpisów przedmiotowo dotyczy przede wszystkim tematu opisanego przez słowa: ",
  main_topic_sentence,
  ". Na podstawie języka używanego przy tym temacie można uznać, że autor ma do niego stosunek: ",
  final_attitude,
  ". Uzasadnienie: ",
  attitude_explanation
)

cat("\n================ RAPORT KOŃCOWY ================\n")
cat("Analizowany plik:", file_path, "\n")
cat("Główny przedmiot tematyczny wpisów:", main_topic_sentence, "\n")
cat("Najważniejsze słowo tematyczne:", main_topic, "\n")
cat("Stosunek autora do głównego tematu:", final_attitude, "\n")
cat("\nSentyment w pobliżu głównego tematu:\n")
cat("Liczba słów pozytywnych przy temacie:", topic_positive, "\n")
cat("Liczba słów negatywnych przy temacie:", topic_negative, "\n")
cat("Wynik przy temacie:", topic_score, "\n")
cat("\nSentyment w całym pliku tekstowym, pomocniczo:\n")
cat("Liczba słów pozytywnych w całym tekście:", positive_count, "\n")
cat("Liczba słów negatywnych w całym tekście:", negative_count, "\n")
cat("Wynik ogólny:", general_score, "\n")
cat("\nWNIOSEK:\n")
cat(final_interpretation, "\n")
cat("================================================\n")

#ZUZIA'S CODE ENDS HERE